In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet

from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


import warnings
warnings.filterwarnings('ignore')

In [104]:
train_df = pd.read_csv("datasets/test.csv")

In [105]:
train_df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,893,20,RL,70.0,8414,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,2,2006,WD,Normal
1,1106,60,RL,98.0,12256,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
2,414,30,RM,56.0,8960,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2010,WD,Normal
3,523,50,RM,50.0,5000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
4,1037,20,RL,89.0,12898,Pave,NaN,IR1,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,9,2009,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,989,60,RL,NaN,12046,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2007,WD,Normal
361,244,160,RL,75.0,10762,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2009,WD,Normal
362,1343,60,RL,NaN,9375,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
363,1058,60,RL,NaN,29959,Pave,NaN,IR2,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2009,WD,Normal
364,1419,20,RL,71.0,9204,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2008,COD,Normal

In [106]:
train_df.columns = [column.lower() for column in train_df.columns]
#train_df.columns = [column.replace(' ','_') for column in train_df.columns]
train_df

,id,mssubclass,mszoning,lotfrontage,lotarea,street,alley,lotshape,landcontour,utilities,...,screenporch,poolarea,poolqc,fence,miscfeature,miscval,mosold,yrsold,saletype,salecondition
0,893,20,RL,70.0,8414,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,2,2006,WD,Normal
1,1106,60,RL,98.0,12256,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
2,414,30,RM,56.0,8960,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2010,WD,Normal
3,523,50,RM,50.0,5000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
4,1037,20,RL,89.0,12898,Pave,NaN,IR1,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,9,2009,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,989,60,RL,NaN,12046,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2007,WD,Normal
361,244,160,RL,75.0,10762,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2009,WD,Normal
362,1343,60,RL,NaN,9375,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
363,1058,60,RL,NaN,29959,Pave,NaN,IR2,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2009,WD,Normal
364,1419,20,RL,71.0,9204,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2008,COD,Normal

### Split DataFrame Based on Type of Feature

In [107]:
#split the data based on type to effectivly explore,impute,and encode if needed. Drop target featurer

#target feature

#categorical features
numeric_train_df = train_df.select_dtypes(include = ['int','float']).sort_index()

#categorical features
categorical_train_df =  train_df.select_dtypes(include = ['object']).sort_index()

# Numeric Features

In [108]:
#remove ID and PID, put into own DF
id_train_df = numeric_train_df[['id']]

numeric_train_df = numeric_train_df.drop(columns = ['id'])

In [109]:
numeric_train_df

,mssubclass,lotfrontage,lotarea,overallqual,overallcond,yearbuilt,yearremodadd,masvnrarea,bsmtfinsf1,bsmtfinsf2,...,garagearea,wooddecksf,openporchsf,enclosedporch,3ssnporch,screenporch,poolarea,miscval,mosold,yrsold
0,20,70.0,8414,6,8,1963,2003,0.0,663,0,...,264,192,0,0,0,0,0,0,2,2006
1,60,98.0,12256,8,5,1994,1995,362.0,1032,0,...,712,186,32,0,0,0,0,0,4,2010
2,30,56.0,8960,5,6,1927,1950,0.0,0,0,...,360,0,0,130,0,0,0,0,3,2010
3,50,50.0,5000,6,7,1947,1950,0.0,399,0,...,420,0,24,36,0,0,0,0,10,2006
4,20,89.0,12898,9,5,2007,2008,70.0,1022,0,...,912,228,0,0,0,0,0,0,9,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,60,NaN,12046,6,6,1976,1976,298.0,156,0,...,551,0,224,0,0,0,0,0,6,2007
361,160,75.0,10762,6,6,1980,1980,0.0,0,0,...,288,0,28,0,0,0,0,0,4,2009
362,60,NaN,9375,8,5,2002,2002,149.0,0,0,...,647,192,87,0,0,0,0,0,8,2007
363,60,NaN,29959,7,6,1994,1994,0.0,595,0,...,467,168,98,0,0,0,0,0,1,2009
364,20,71.0,9204,5,5,1963,1963,0.0,25,872,...,336,0,88,0,0,0,0,0,8,2008

In [110]:
numeric_null = numeric_train_df.isna().sum().sort_values(ascending = False)
numeric_null[numeric_null > 0]

lotfrontage    59
garageyrblt    23
masvnrarea      4
dtype: int64

#### Numeric categories that could mean 0 for NA

In [111]:
def na_0_filler(df,columns):
    for column in columns:
        df[column] = df[column].fillna(0)
    return df

In [112]:
#Linear feet of street connected to property
#reasonable to assume if na, zero feet of street connected to property 
numeric_train_df[['lotfrontage']]

#Year garage was built
#reasonable to assume if na, no garage
numeric_train_df[['garageyrblt']]

#Masonry veneer area in square feet
#reasonable to assume if na, no Masonry veneer
numeric_train_df[['masvnrarea']].describe()

numeric_na_0_columns = ['garageyrblt','masvnrarea','lotfrontage']

In [113]:
na_0_filler(numeric_train_df,[numeric_na_0_columns]).head()

,mssubclass,lotfrontage,lotarea,overallqual,overallcond,yearbuilt,yearremodadd,masvnrarea,bsmtfinsf1,bsmtfinsf2,...,garagearea,wooddecksf,openporchsf,enclosedporch,3ssnporch,screenporch,poolarea,miscval,mosold,yrsold
0,20,70.0,8414,6,8,1963,2003,0.0,663,0,...,264,192,0,0,0,0,0,0,2,2006
1,60,98.0,12256,8,5,1994,1995,362.0,1032,0,...,712,186,32,0,0,0,0,0,4,2010
2,30,56.0,8960,5,6,1927,1950,0.0,0,0,...,360,0,0,130,0,0,0,0,3,2010
3,50,50.0,5000,6,7,1947,1950,0.0,399,0,...,420,0,24,36,0,0,0,0,10,2006
4,20,89.0,12898,9,5,2007,2008,70.0,1022,0,...,912,228,0,0,0,0,0,0,9,2009

#### Numeric categories that could need inputer

In [114]:
imputer = SimpleImputer(strategy='median')

In [115]:
#all columns have one missing value, will use the median value to fill na values

imputer_columns = ['garagecars','garagearea']

In [116]:
numeric_train_df[imputer_columns] = imputer.fit_transform(numeric_train_df[imputer_columns])
numeric_train_df

,mssubclass,lotfrontage,lotarea,overallqual,overallcond,yearbuilt,yearremodadd,masvnrarea,bsmtfinsf1,bsmtfinsf2,...,garagearea,wooddecksf,openporchsf,enclosedporch,3ssnporch,screenporch,poolarea,miscval,mosold,yrsold
0,20,70.0,8414,6,8,1963,2003,0.0,663,0,...,264.0,192,0,0,0,0,0,0,2,2006
1,60,98.0,12256,8,5,1994,1995,362.0,1032,0,...,712.0,186,32,0,0,0,0,0,4,2010
2,30,56.0,8960,5,6,1927,1950,0.0,0,0,...,360.0,0,0,130,0,0,0,0,3,2010
3,50,50.0,5000,6,7,1947,1950,0.0,399,0,...,420.0,0,24,36,0,0,0,0,10,2006
4,20,89.0,12898,9,5,2007,2008,70.0,1022,0,...,912.0,228,0,0,0,0,0,0,9,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,60,0.0,12046,6,6,1976,1976,298.0,156,0,...,551.0,0,224,0,0,0,0,0,6,2007
361,160,75.0,10762,6,6,1980,1980,0.0,0,0,...,288.0,0,28,0,0,0,0,0,4,2009
362,60,0.0,9375,8,5,2002,2002,149.0,0,0,...,647.0,192,87,0,0,0,0,0,8,2007
363,60,0.0,29959,7,6,1994,1994,0.0,595,0,...,467.0,168,98,0,0,0,0,0,1,2009
364,20,71.0,9204,5,5,1963,1963,0.0,25,872,...,336.0,0,88,0,0,0,0,0,8,2008

## Standard Scalar

In [117]:
ss = StandardScaler()

In [118]:
scaled_numeric_train_df = ss.fit_transform(numeric_train_df,)
scaled_numeric_train_df = pd.DataFrame(scaled_numeric_train_df,index = numeric_train_df.index, columns=numeric_train_df.columns)

In [119]:
scaled_numeric_train_df

,mssubclass,lotfrontage,lotarea,overallqual,overallcond,yearbuilt,yearremodadd,masvnrarea,bsmtfinsf1,bsmtfinsf2,...,garagearea,wooddecksf,openporchsf,enclosedporch,3ssnporch,screenporch,poolarea,miscval,mosold,yrsold
0,-0.877156,0.378322,-0.255419,-0.005761,2.115349,-0.302103,0.888098,-0.502225,0.517281,-0.302049,...,-0.877057,0.954269,-0.676104,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,-1.518757,-1.354405
1,0.091198,1.252493,0.439482,1.396049,-0.522814,0.768457,0.495598,1.254419,1.336581,-0.302049,...,1.134816,0.899006,-0.102827,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,-0.796011,1.641704
2,-0.635067,-0.058763,-0.156664,-0.706666,0.356574,-1.545335,-1.712212,-0.502225,-0.954795,-0.302049,...,-0.445941,-0.814167,-0.676104,1.745691,-0.103994,-0.238908,-0.052414,-0.064429,-1.157384,1.641704
3,-0.150891,-0.246085,-0.872907,-0.005761,1.235962,-0.854651,-1.712212,-0.502225,-0.068885,-0.302049,...,-0.176494,-0.814167,-0.246146,0.190874,-0.103994,-0.238908,-0.052414,-0.064429,1.372227,-1.354405
4,-0.877156,0.971509,0.555600,2.096954,-0.522814,1.217402,1.133410,-0.162542,1.314378,-0.302049,...,2.032974,1.285851,-0.676104,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,1.010854,0.892676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,0.091198,-1.807103,0.401499,-0.005761,0.356574,0.146841,-0.436589,0.943852,-0.608424,-0.302049,...,0.411799,-0.814167,3.336836,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,-0.073265,-0.605378
361,2.512081,0.534424,0.169263,-0.005761,0.356574,0.284978,-0.240339,-0.502225,-0.954795,-0.302049,...,-0.769278,-0.814167,-0.174486,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,-0.796011,0.892676
362,0.091198,-1.807103,-0.081603,1.396049,-0.522814,1.044731,0.839035,0.220814,-0.954795,-0.302049,...,0.842915,0.954269,0.882493,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,0.649481,-0.605378
363,0.091198,-1.807103,3.641414,0.695144,0.356574,0.768457,0.446535,-0.502225,0.366299,-0.302049,...,0.034573,0.733215,1.079557,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,-1.880130,0.892676
364,-0.877156,0.409543,-0.112532,-0.706666,-0.522814,-0.302103,-1.074400,-0.502225,-0.899287,4.502118,...,-0.553720,-0.814167,0.900408,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,0.649481,0.143649

In [120]:
id_train_df

       id
0     893
1    1106
2     414
3     523
4    1037
..    ...
360   989
361   244
362  1343
363  1058
364  1419

[365 rows x 1 columns]

In [121]:
#add id and PID back to numeric column
scaled_numeric_train_df = pd.concat([id_train_df,scaled_numeric_train_df], axis=1)
scaled_numeric_train_df

,id,mssubclass,lotfrontage,lotarea,overallqual,overallcond,yearbuilt,yearremodadd,masvnrarea,bsmtfinsf1,...,garagearea,wooddecksf,openporchsf,enclosedporch,3ssnporch,screenporch,poolarea,miscval,mosold,yrsold
0,893,-0.877156,0.378322,-0.255419,-0.005761,2.115349,-0.302103,0.888098,-0.502225,0.517281,...,-0.877057,0.954269,-0.676104,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,-1.518757,-1.354405
1,1106,0.091198,1.252493,0.439482,1.396049,-0.522814,0.768457,0.495598,1.254419,1.336581,...,1.134816,0.899006,-0.102827,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,-0.796011,1.641704
2,414,-0.635067,-0.058763,-0.156664,-0.706666,0.356574,-1.545335,-1.712212,-0.502225,-0.954795,...,-0.445941,-0.814167,-0.676104,1.745691,-0.103994,-0.238908,-0.052414,-0.064429,-1.157384,1.641704
3,523,-0.150891,-0.246085,-0.872907,-0.005761,1.235962,-0.854651,-1.712212,-0.502225,-0.068885,...,-0.176494,-0.814167,-0.246146,0.190874,-0.103994,-0.238908,-0.052414,-0.064429,1.372227,-1.354405
4,1037,-0.877156,0.971509,0.555600,2.096954,-0.522814,1.217402,1.133410,-0.162542,1.314378,...,2.032974,1.285851,-0.676104,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,1.010854,0.892676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,989,0.091198,-1.807103,0.401499,-0.005761,0.356574,0.146841,-0.436589,0.943852,-0.608424,...,0.411799,-0.814167,3.336836,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,-0.073265,-0.605378
361,244,2.512081,0.534424,0.169263,-0.005761,0.356574,0.284978,-0.240339,-0.502225,-0.954795,...,-0.769278,-0.814167,-0.174486,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,-0.796011,0.892676
362,1343,0.091198,-1.807103,-0.081603,1.396049,-0.522814,1.044731,0.839035,0.220814,-0.954795,...,0.842915,0.954269,0.882493,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,0.649481,-0.605378
363,1058,0.091198,-1.807103,3.641414,0.695144,0.356574,0.768457,0.446535,-0.502225,0.366299,...,0.034573,0.733215,1.079557,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,-1.880130,0.892676
364,1419,-0.877156,0.409543,-0.112532,-0.706666,-0.522814,-0.302103,-1.074400,-0.502225,-0.899287,...,-0.553720,-0.814167,0.900408,-0.404588,-0.103994,-0.238908,-0.052414,-0.064429,0.649481,0.143649

# Categorical Features

#### Ordinal Features

In [122]:
ordinal_columns = ['alley','utilities','landslope','exterqual',
       'bsmtqual', 'bsmtcond', 'bsmtexposure','bsmtfintype1',
        'bsmtfintype2', 'heatingqc','electrical', 'kitchenqual', 
        'functional','fireplacequ', 'garagefinish', 'garagequal',
        'garagecond', 'paveddrive', 'poolqc', 'fence'] 


ordinal_train_df = categorical_train_df[ordinal_columns]

In [123]:
ordinal_null = ordinal_train_df.isna().sum().sort_values(ascending = False)
ordinal_null[ordinal_null > 0]
ordinal_na_0_columns = ordinal_null[ordinal_null > 0].index

#### Ordinal categories that could mean 0 for NA

In [124]:
na_0_filler(ordinal_train_df,ordinal_na_0_columns)

,alley,utilities,landslope,exterqual,bsmtqual,bsmtcond,bsmtexposure,bsmtfintype1,bsmtfintype2,heatingqc,electrical,kitchenqual,functional,fireplacequ,garagefinish,garagequal,garagecond,paveddrive,poolqc,fence
0,0,AllPub,Gtl,TA,TA,TA,No,GLQ,Unf,TA,SBrkr,TA,Typ,0,RFn,TA,TA,Y,0,MnPrv
1,0,AllPub,Gtl,Gd,Ex,TA,Av,GLQ,Unf,Ex,SBrkr,Gd,Typ,TA,RFn,TA,TA,Y,0,0
2,Grvl,AllPub,Gtl,TA,TA,TA,No,Unf,Unf,Gd,FuseA,TA,Typ,Gd,Unf,TA,TA,Y,0,0
3,0,AllPub,Gtl,TA,TA,TA,No,ALQ,Unf,Ex,SBrkr,TA,Typ,Gd,Unf,TA,TA,Y,0,0
4,0,AllPub,Gtl,Gd,Ex,TA,Gd,GLQ,Unf,Ex,SBrkr,Ex,Typ,Ex,Fin,TA,TA,Y,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,0,AllPub,Gtl,TA,TA,TA,No,LwQ,Unf,TA,SBrkr,Gd,Typ,TA,Fin,TA,TA,Y,0,0
361,0,AllPub,Gtl,TA,Gd,TA,No,Unf,Unf,TA,SBrkr,TA,Typ,TA,RFn,TA,TA,Y,0,0
362,0,AllPub,Gtl,Gd,Gd,TA,No,Unf,Unf,Ex,SBrkr,Gd,Typ,Gd,RFn,TA,TA,Y,0,0
363,0,AllPub,Gtl,Gd,Gd,TA,No,GLQ,Unf,Ex,SBrkr,Gd,Typ,Gd,Fin,TA,TA,Y,0,0
364,0,AllPub,Gtl,TA,TA,TA,No,BLQ,Rec,TA,SBrkr,TA,Typ,0,Unf,TA,TA,Y,0,0

In [125]:
ordinal_null = ordinal_train_df.isna().sum().sort_values(ascending = False)
ordinal_null[ordinal_null > 0]

Series([], dtype: int64)

## Nominal Features

In [126]:
nominal_train_df = categorical_train_df.drop(columns = ordinal_columns)
nominal_train_df.head()

,mszoning,street,lotshape,landcontour,lotconfig,neighborhood,condition1,condition2,bldgtype,housestyle,...,exterior2nd,masvnrtype,extercond,foundation,heating,centralair,garagetype,miscfeature,saletype,salecondition
0,RL,Pave,Reg,Lvl,Inside,Sawyer,Norm,Norm,1Fam,1Story,...,HdBoard,None,TA,CBlock,GasA,Y,Attchd,NaN,WD,Normal
1,RL,Pave,IR1,Lvl,Corner,NoRidge,Norm,Norm,1Fam,2Story,...,HdBoard,BrkFace,TA,PConc,GasA,Y,Attchd,NaN,WD,Normal
2,RM,Pave,Reg,Lvl,Inside,OldTown,Artery,Norm,1Fam,1Story,...,Wd Shng,None,TA,CBlock,GasA,Y,Detchd,NaN,WD,Normal
3,RM,Pave,Reg,Lvl,Corner,BrkSide,Feedr,Norm,1Fam,1.5Fin,...,CmentBd,None,Gd,CBlock,GasA,Y,Detchd,NaN,WD,Normal
4,RL,Pave,IR1,HLS,Inside,Timber,Norm,Norm,1Fam,1Story,...,VinylSd,Stone,TA,PConc,GasA,Y,Attchd,NaN,WD,Normal

In [127]:
nominal_null = nominal_train_df.isna().sum().sort_values(ascending = False)
nominal_null[nominal_null > 0]

miscfeature    354
garagetype      23
masvnrtype       4
dtype: int64

#### Nominal categories that could mean 0 for NA

In [128]:
#Miscellaneous feature not covered in other categories, na means 0
nominal_train_df['miscfeature']

#Garage location, na means 0
nominal_train_df['garagetype']

#Masonry veneer type, it could be none but was put in as na. Na will mean 0
nominal_train_df['masvnrtype'].isna().sum()
nominal_na_0_columns = nominal_null[nominal_null > 0].index

In [129]:
na_0_filler(nominal_train_df,nominal_na_0_columns)

,mszoning,street,lotshape,landcontour,lotconfig,neighborhood,condition1,condition2,bldgtype,housestyle,...,exterior2nd,masvnrtype,extercond,foundation,heating,centralair,garagetype,miscfeature,saletype,salecondition
0,RL,Pave,Reg,Lvl,Inside,Sawyer,Norm,Norm,1Fam,1Story,...,HdBoard,None,TA,CBlock,GasA,Y,Attchd,0,WD,Normal
1,RL,Pave,IR1,Lvl,Corner,NoRidge,Norm,Norm,1Fam,2Story,...,HdBoard,BrkFace,TA,PConc,GasA,Y,Attchd,0,WD,Normal
2,RM,Pave,Reg,Lvl,Inside,OldTown,Artery,Norm,1Fam,1Story,...,Wd Shng,None,TA,CBlock,GasA,Y,Detchd,0,WD,Normal
3,RM,Pave,Reg,Lvl,Corner,BrkSide,Feedr,Norm,1Fam,1.5Fin,...,CmentBd,None,Gd,CBlock,GasA,Y,Detchd,0,WD,Normal
4,RL,Pave,IR1,HLS,Inside,Timber,Norm,Norm,1Fam,1Story,...,VinylSd,Stone,TA,PConc,GasA,Y,Attchd,0,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,RL,Pave,IR1,Lvl,Inside,NWAmes,Norm,Norm,1Fam,2Story,...,Plywood,BrkFace,TA,CBlock,GasA,Y,Attchd,0,WD,Normal
361,RL,Pave,Reg,Lvl,Corner,SawyerW,Norm,Norm,TwnhsE,2Story,...,Plywood,None,TA,CBlock,GasA,Y,Attchd,0,WD,Normal
362,RL,Pave,Reg,Lvl,Inside,CollgCr,Norm,Norm,1Fam,2Story,...,VinylSd,BrkFace,TA,PConc,GasA,Y,Attchd,0,WD,Normal
363,RL,Pave,IR2,Lvl,FR2,NoRidge,Norm,Norm,1Fam,2Story,...,HdBoard,None,TA,PConc,GasA,Y,BuiltIn,0,WD,Normal
364,RL,Pave,Reg,Lvl,Inside,NAmes,Norm,Norm,1Fam,1Story,...,HdBoard,None,TA,CBlock,GasA,Y,Detchd,0,COD,Normal

## Encoding Ordinal Features

### Ordinal Dictionary

In [130]:
ordinal_col_list = ordinal_train_df.columns
print(ordinal_col_list)

Index(['alley', 'utilities', 'landslope', 'exterqual', 'bsmtqual', 'bsmtcond',
       'bsmtexposure', 'bsmtfintype1', 'bsmtfintype2', 'heatingqc',
       'electrical', 'kitchenqual', 'functional', 'fireplacequ',
       'garagefinish', 'garagequal', 'garagecond', 'paveddrive', 'poolqc',
       'fence'],
      dtype='object')

In [131]:
ordinal_dict = [
    
#Alley
{'Grvl':2,'Pave':1,0:0},
#Utilities
{'AllPub':4,'NoSewr':3,'NoSeWa':2,'ELO':1},
#Land Slope
{'Gtl':3,'Mod':2,'Sev':1},
#Exter Qual
{'Ex':5,'Gd':4, 'TA':3, 'Fa':2,'Po':1},     
#Bsmt Qual
{'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1,0:0},
#Bsmt Cond
{'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1,0:0},
#Bsmt Exposure
{'Gd':4,'Av':3,'Mn':2,'No':1,0:0},
#BsmtFin Type 1
{'GLQ':6,'ALQ':5,'BLQ':4,'Rec':3,'LwQ':2,'Unf':1,0:0},
#BsmtFinType 2
{'GLQ':6,'ALQ':5,'BLQ':4,'Rec':3,'LwQ':2,'Unf':1,0:0},
#HeatingQC 
{'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1},
#Electrical
{'SBrkr':5,'FuseA':4,'FuseF':3,'FuseP':2,'Mix':1,0:0},
#KitchenQual
{'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1},
#Functional
{'Typ':8,'Min1':7,'Min2':6,'Mod':5,'Maj1':4,'Maj2':3,'Sev':2,'Sal':1},
#FireplaceQu
{'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1,0:0},
#Garage Finish
{'Fin':3,'RFn':2,'Unf':1,0:0},
#Garage Qual
{'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1,0:0},
#Garage Cond
{'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1,0:0},
#Paved Drive
{'Y':3,'P':2,'N':1},
#Pool QC
{'Ex':5,'Gd':4,'TA':3,'Fa':2,'Po':1,0:0},
#Fence
{'GdPrv':4,'MnPrv':3,'GdWo':2,'MnWw':1,0:0}

]

In [132]:
#zip column names to dictionary values
named_ordinal_dict = dict(zip(ordinal_train_df.columns,ordinal_dict))

In [133]:
def ordinal_replace(df,columns):
    new_df = df
    for column in columns:
        new_df[column] = new_df[column].map(named_ordinal_dict[column])
    return new_df

In [134]:
#replace categorty value with values
encoded_ordinal_train_df = ordinal_replace(ordinal_train_df, ordinal_train_df.columns)

In [135]:
encoded_ordinal_train_df.head()

,alley,utilities,landslope,exterqual,bsmtqual,bsmtcond,bsmtexposure,bsmtfintype1,bsmtfintype2,heatingqc,electrical,kitchenqual,functional,fireplacequ,garagefinish,garagequal,garagecond,paveddrive,poolqc,fence
0,0,4,3,3,3,3,1,6,1,3,5,3,8,0,2,3,3,3,0,3
1,0,4,3,4,5,3,3,6,1,5,5,4,8,3,2,3,3,3,0,0
2,2,4,3,3,3,3,1,1,1,4,4,3,8,4,1,3,3,3,0,0
3,0,4,3,3,3,3,1,5,1,5,5,3,8,4,1,3,3,3,0,0
4,0,4,3,4,5,3,4,6,1,5,5,5,8,5,3,3,3,3,0,0

### Encoding Nominal Features

In [136]:
#all 0 values replaced from NA should be dropped when encoded.
dummies_nominal_train_df = pd.get_dummies(nominal_train_df, drop_first=True)

## Combine all dataframes back to one and save

In [137]:
#numerical, ordinal, and nominal data frames created earlier
dataframes = [scaled_numeric_train_df,encoded_ordinal_train_df,dummies_nominal_train_df]

In [138]:
#combine on index
cleaned_train_data = pd.concat(dataframes, axis=1)
cleaned_train_data

,id,mssubclass,lotfrontage,lotarea,overallqual,overallcond,yearbuilt,yearremodadd,masvnrarea,bsmtfinsf1,...,saletype_ConLD,saletype_ConLI,saletype_ConLw,saletype_New,saletype_Oth,saletype_WD,salecondition_Alloca,salecondition_Family,salecondition_Normal,salecondition_Partial
0,893,-0.877156,0.378322,-0.255419,-0.005761,2.115349,-0.302103,0.888098,-0.502225,0.517281,...,0,0,0,0,0,1,0,0,1,0
1,1106,0.091198,1.252493,0.439482,1.396049,-0.522814,0.768457,0.495598,1.254419,1.336581,...,0,0,0,0,0,1,0,0,1,0
2,414,-0.635067,-0.058763,-0.156664,-0.706666,0.356574,-1.545335,-1.712212,-0.502225,-0.954795,...,0,0,0,0,0,1,0,0,1,0
3,523,-0.150891,-0.246085,-0.872907,-0.005761,1.235962,-0.854651,-1.712212,-0.502225,-0.068885,...,0,0,0,0,0,1,0,0,1,0
4,1037,-0.877156,0.971509,0.555600,2.096954,-0.522814,1.217402,1.133410,-0.162542,1.314378,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,989,0.091198,-1.807103,0.401499,-0.005761,0.356574,0.146841,-0.436589,0.943852,-0.608424,...,0,0,0,0,0,1,0,0,1,0
361,244,2.512081,0.534424,0.169263,-0.005761,0.356574,0.284978,-0.240339,-0.502225,-0.954795,...,0,0,0,0,0,1,0,0,1,0
362,1343,0.091198,-1.807103,-0.081603,1.396049,-0.522814,1.044731,0.839035,0.220814,-0.954795,...,0,0,0,0,0,1,0,0,1,0
363,1058,0.091198,-1.807103,3.641414,0.695144,0.356574,0.768457,0.446535,-0.502225,0.366299,...,0,0,0,0,0,1,0,0,1,0
364,1419,-0.877156,0.409543,-0.112532,-0.706666,-0.522814,-0.302103,-1.074400,-0.502225,-0.899287,...,0,0,0,0,0,0,0,0,1,0

In [139]:
#write new cleaned and encoded dataframes
cleaned_train_data.to_csv('datasets/final_kaggle_data.csv',index=False)